export const STONES = [
  {
    id: 'mind',
    index: '01',
    name: 'MIND STONE',
    roman: 'I',
    colorHex: '#ffd000',
    colorThree: 0xffd000,
    coreColor: 0xfff08a,
    darkColor: 0x665500,
    domainKey: 'intelligence',
    domain: 'INTELLIGENCE',
    domainTagline: 'AI • ML • Decision Systems',
    marvelTheme: 'Vision Neural Gold',
    entity: 'The Scepter / Vision\'s Core',
    origin: 'Chitauri Scepter / Neural Matrix',
    vessel: 'The Scepter / Vision',
    frequency: '528.00 THz',
    refractiveIndex: '2.54',
    powerLevel: '98.5%',
    particleCount: 180,
    techStack: ['Python', 'PyTorch', 'LangChain', 'FastAPI', 'Gemini API', 'TensorFlow'],
    quote: 'It contains an intellect of supreme cosmic density.',
    description: 'Architect autonomous multi-agent networks, neural cognition models, self-refining LLM pipelines, and intelligent decision systems capable of enterprise-scale problem-solving.',
    stats: [
      { label: 'SYNAPSE DENSITY', value: 'Infinite' },
      { label: 'MODEL CAPACITY', value: 'Trillion Param' },
      { label: 'HARMONIC', value: '528.00 THz' },
      { label: 'SLOTS OPEN', value: '12 Squads' }
    ]
  },
  {
    id: 'space',
    index: '02',
    name: 'SPACE STONE',
    roman: 'II',
    colorHex: '#00d2ff',
    colorThree: 0x00d2ff,
    coreColor: 0x80ecff,
    darkColor: 0x004066,
    domainKey: 'connectivity',
    domain: 'CONNECTIVITY',
    domainTagline: 'Cybersecurity • Cloud • Networks',
    marvelTheme: 'Tesseract Cyan',
    entity: 'Tesseract (Cosmic Cube)',
    origin: 'Pre-Universe Singularity / Asgardian Vault',
    vessel: 'The Tesseract',
    frequency: '432.18 THz',
    refractiveIndex: '2.42',
    powerLevel: '99.2%',
    particleCount: 160,
    techStack: ['Rust', 'Go', 'Kubernetes', 'eBPF', 'Cloudflare Workers', 'WireGuard'],
    quote: 'The Tesseract has awakened. It is on a little world, a human world.',
    description: 'Forge zero-trust defense architectures, planet-scale cloud networks, high-throughput distributed protocols, and resilient cybersecurity fabrics.',
    stats: [
      { label: 'LATENCY PROFILE', value: 'Sub-5ms Mesh' },
      { label: 'DEFENSE MATRIX', value: 'Post-Quantum' },
      { label: 'HARMONIC', value: '432.18 THz' },
      { label: 'SLOTS OPEN', value: '10 Squads' }
    ]
  },
  {
    id: 'reality',
    index: '03',
    name: 'REALITY STONE',
    roman: 'III',
    colorHex: '#ff2a4b',
    colorThree: 0xff2a4b,
    coreColor: 0xff7588,
    darkColor: 0x660010,
    domainKey: 'digital',
    domain: 'DIGITAL',
    domainTagline: 'Web • Mobile • Digital Platforms',
    marvelTheme: 'Aether Crimson',
    entity: 'The Aether (Fluid Crystal)',
    origin: 'Pre-Universe Singularity / Svartalfheim',
    vessel: 'The Aether Prism',
    frequency: '612.44 THz',
    refractiveIndex: '2.68',
    powerLevel: '97.8%',
    particleCount: 220,
    techStack: ['TypeScript', 'React', 'Flutter', 'Next.js', 'Node.js', 'WebGL'],
    quote: 'It turns matter into dark matter, reshaping physical reality at will.',
    description: 'Bend digital reality. Build hyper-responsive web applications, cross-platform mobile architectures, immersive real-time canvases, and scalable modern platforms.',
    stats: [
      { label: 'RENDER TARGET', value: '120 FPS WebGL' },
      { label: 'STATE CONFLICT', value: 'Sub-30ms CRDT' },
      { label: 'HARMONIC', value: '612.44 THz' },
      { label: 'SLOTS OPEN', value: '14 Squads' }
    ]
  },
  {
    id: 'power',
    index: '04',
    name: 'POWER STONE',
    roman: 'IV',
    colorHex: '#b026ff',
    colorThree: 0xb026ff,
    coreColor: 0xe085ff,
    darkColor: 0x4a0572,
    domainKey: 'automation',
    domain: 'AUTOMATION',
    domainTagline: 'IoT • Robotics • Embedded Systems',
    marvelTheme: 'Thanos Void Purple',
    entity: 'The Orb / Morag Temple',
    origin: 'Pre-Universe Singularity / Celestial Eson',
    vessel: 'The Orb of Morag',
    frequency: '741.89 THz',
    refractiveIndex: '2.75',
    powerLevel: '100.0%',
    particleCount: 200,
    techStack: ['C++', 'Rust', 'ESP32 / Arduino', 'ROS2', 'MQTT', 'FreeRTOS'],
    quote: 'It contains an energy that destroys all organic matter it touches.',
    description: 'Unleash physical and digital kinetic power. Develop autonomous robotics, smart hardware controllers, industrial IoT pipelines, and embedded real-time systems.',
    stats: [
      { label: 'BUS TELEMETRY', value: 'Microsecond' },
      { label: 'KINETIC FAILOVER', value: 'Autonomous Swarm' },
      { label: 'HARMONIC', value: '741.89 THz' },
      { label: 'SLOTS OPEN', value: '8 Squads' }
    ]
  },
  {
    id: 'time',
    index: '05',
    name: 'TIME STONE',
    roman: 'V',
    colorHex: '#00ff88',
    colorThree: 0x00ff88,
    coreColor: 0x8affc1,
    darkColor: 0x00552b,
    domainKey: 'analytics',
    domain: 'ANALYTICS',
    domainTagline: 'Data • Prediction • Optimization',
    marvelTheme: 'Doctor Strange Emerald',
    entity: 'Eye of Agamotto / Kamar-Taj',
    origin: 'Pre-Universe Singularity / Sorcerer Supreme',
    vessel: 'Eye of Agamotto',
    frequency: '852.12 THz',
    refractiveIndex: '2.48',
    powerLevel: '98.9%',
    particleCount: 190,
    techStack: ['Python', 'Kafka', 'ClickHouse', 'Pandas', 'DuckDB', 'Scikit-Learn'],
    quote: 'Dormammu, I have come to bargain.',
    description: 'Control temporal velocity. Engineer real-time streaming pipelines, high-throughput predictive time-series models, algorithmic optimization engines, and big data intelligence.',
    stats: [
      { label: 'STREAM INGEST', value: '1M Events/sec' },
      { label: 'ORACLE HORIZON', value: '14,000,605 Paths' },
      { label: 'HARMONIC', value: '852.12 THz' },
      { label: 'SLOTS OPEN', value: '11 Squads' }
    ]
  },
  {
    id: 'soul',
    index: '06',
    name: 'SOUL STONE',
    roman: 'VI',
    colorHex: '#ff7700',
    colorThree: 0xff7700,
    coreColor: 0xffd27f,
    darkColor: 0x994400,
    domainKey: 'impact',
    domain: 'IMPACT',
    domainTagline: 'Healthcare • Agriculture • Education • Social Good',
    marvelTheme: 'Vormir Sunset Orange',
    entity: 'Vormir Altar / Soul World',
    origin: 'Pre-Universe Singularity / Red Skull Guardian',
    vessel: 'Vormir Shrine',
    frequency: '963.00 THz',
    refractiveIndex: '2.62',
    powerLevel: '99.7%',
    particleCount: 180,
    techStack: ['Python', 'Flutter', 'PostgreSQL', 'FastAPI', 'Edge AI', 'OpenCV'],
    quote: 'A soul for a soul. Great technological impact demands great purpose.',
    description: 'Channel technology to transform lives. Pioneer accessible healthcare diagnostics, precision agricultural sensors, adaptive educational tools, and sustainable social impact networks.',
    stats: [
      { label: 'COMMUNITY REACH', value: 'Global Impact' },
      { label: 'ETHICAL CORE', value: 'Privacy-Preserving' },
      { label: 'HARMONIC', value: '963.00 THz' },
      { label: 'SLOTS OPEN', value: '15 Squads' }
    ]
  }
];
