export const TIMELINE_EVENTS = [
  {
    id: 'registration-phase',
    stone: 'all',
    stoneName: 'ALL DOMAINS',
    stoneColor: '#ffffff',
    stoneRgb: '255, 255, 255',
    date: 'OCTOBER 01 - 10',
    era: 'Pre-Hack Phase',
    title: 'Squad Commissioning & Domain Locking',
    location: 'Online Registration Portal',
    vessel: 'Cloudflare R2 Verification Engine',
    wielders: 'All Collegiate Squads (3–4 Members)',
    desc: 'Squads assemble their teams, choose an Infinity Stone domain, remit the ₹390/member fee, and upload payment screenshots. The automated UTR engine validates unique transaction references in real time.'
  },
  {
    id: 'ps-release',
    stone: 'mind',
    stoneName: 'MIND // INTELLIGENCE',
    stoneColor: '#ffd000',
    stoneRgb: '255, 208, 0',
    date: 'DAY -2 // 09:00 AM',
    era: '48H Prior',
    title: 'Problem Statements Unlocked',
    location: 'Team Leader Portal',
    vessel: 'Singularity Problem Dossier',
    wielders: 'Confirmed Team Leaders',
    desc: 'Organizer Command post unlocks the classified problem statements 1-2 days before the hack. Leaders log in to evaluate challenges across the 6 domains and lock their preferred problem statement.'
  },
  {
    id: 'check-in-breakfast',
    stone: 'space',
    stoneName: 'SPACE // CONNECTIVITY',
    stoneColor: '#00d2ff',
    stoneRgb: '0, 210, 255',
    date: 'DAY 1 // 08:00 AM',
    era: 'Morning Ingress',
    title: 'Campus Ingress, RFID Badges & Breakfast Drop',
    location: 'GVPCDPGC Campus, Visakhapatnam',
    vessel: 'Hacker Welcome Kit & NFC Wristband',
    wielders: 'Coordinators & Registered Hackers',
    desc: 'Arrival at the campus. Coordinators scan leader QR passes, issue branded hacker kits, allocate team lab benches, and distribute hot breakfast meal tokens (Item: Breakfast Token #1).'
  },
  {
    id: 'kickoff-commence',
    stone: 'power',
    stoneName: 'POWER // AUTOMATION',
    stoneColor: '#b026ff',
    stoneRgb: '176, 38, 255',
    date: 'DAY 1 // 10:00 AM',
    era: 'Hacking Begins',
    title: 'Opening Ceremony & 36H Clock Ignition',
    location: 'Grand Central Auditorium',
    vessel: 'Infinity Timer & Cloud Gateways',
    wielders: 'Patrons, Mentors & All Hackers',
    desc: 'Keynote address by industry CTOs from Cloudflare and AWS. The 36-hour countdown clock initiates on the main arena monitors. Hacking commences across all 6 specialized lab domains.'
  },
  {
    id: 'mentoring-hightea',
    stone: 'reality',
    stoneName: 'REALITY // DIGITAL',
    stoneColor: '#ff2a4b',
    stoneRgb: '255, 42, 75',
    date: 'DAY 1 // 04:00 PM',
    era: 'Phase 1 Mentorship',
    title: 'Domain Mentor Clinic & High Tea Fuel',
    location: 'Lab Blocks & Dining Quad',
    vessel: 'High Tea Token & Energy Station',
    wielders: 'Frontier Tech Mentors',
    desc: 'Specialized domain mentors rotate across team pods to critique system architecture. Coordinators check off High Tea meal tokens providing fresh artisanal snacks and piping hot filter coffee.'
  },
  {
    id: 'review-round-1',
    stone: 'time',
    stoneName: 'TIME // ANALYTICS',
    stoneColor: '#00ff88',
    stoneRgb: '0, 255, 136',
    date: 'DAY 1 // 07:30 PM',
    era: 'Milestone Review 01',
    title: 'Review 1: Architecture & Idea Feasibility',
    location: 'Evaluation Pods',
    vessel: 'Coordinator Desk & Review Ledger',
    wielders: 'Panels of Industry Evaluators',
    desc: 'Coordinators mark teams attending Review 1. Judges evaluate schema designs, repository scaffolds, and domain relevance. Numerical scores are logged securely to R2 and kept hidden from team dashboards.'
  },
  {
    id: 'asgard-dinner',
    stone: 'soul',
    stoneName: 'SOUL // IMPACT',
    stoneColor: '#ff7700',
    stoneRgb: '255, 119, 0',
    date: 'DAY 1 // 09:30 PM',
    era: 'Culinary Fuel',
    title: 'Feast of Vormir: Hot Dinner Buffet',
    location: 'Campus Courtyard Banquet',
    vessel: 'Dinner Token Verification',
    wielders: 'All Hackers & Coordinators',
    desc: 'Multi-cuisine banquet dinner for all registered participants. Coordinators verify digital meal tokens to ensure seamless, rapid service without disrupting code flow.'
  },
  {
    id: 'midnight-fuel',
    stone: 'power',
    stoneName: 'POWER // AUTOMATION',
    stoneColor: '#b026ff',
    stoneRgb: '176, 38, 255',
    date: 'DAY 2 // 01:30 AM',
    era: 'Graveyard Shift',
    title: 'Midnight Fuel, Energy Drinks & VR Jam',
    location: 'Infinity Lounge & Gaming Arenas',
    vessel: 'Caffeine & Midnight Energy Snacks',
    wielders: 'Night Owl Developers',
    desc: 'Red Bull drops, pizza bites, retro arcade tournaments, and acoustic musical chill breaks to recharge hacker momentum through the core development sprint.'
  },
  {
    id: 'review-round-2',
    stone: 'space',
    stoneName: 'SPACE // CONNECTIVITY',
    stoneColor: '#00d2ff',
    stoneRgb: '0, 210, 255',
    date: 'DAY 2 // 09:30 AM',
    era: 'Milestone Review 02',
    title: 'Review 2: Mid-way Logic & Live Integration',
    location: 'Domain Hubs',
    vessel: 'Coordinator R2 Check-In',
    wielders: 'Technical Judges & Squads',
    desc: 'Evaluators inspect functioning backend APIs, frontend states, hardware sensor feeds, and edge database bindings. Coordinators verify Review 2 attendance.'
  },
  {
    id: 'lunch-sprint',
    stone: 'reality',
    stoneName: 'REALITY // DIGITAL',
    stoneColor: '#ff2a4b',
    stoneRgb: '255, 42, 75',
    date: 'DAY 2 // 01:30 PM',
    era: 'Final Push',
    title: 'Lunch Drop & Deployment Freeze Window',
    location: 'Dining Quad & Workstations',
    vessel: 'Lunch Token #5',
    wielders: 'All Squads',
    desc: 'Final meal drop. 2-hour code freeze countdown commences. Teams commit repositories, record video demo fallbacks, and rehearse live pitches.'
  },
  {
    id: 'review-round-3',
    stone: 'mind',
    stoneName: 'MIND // INTELLIGENCE',
    stoneColor: '#ffd000',
    stoneRgb: '255, 208, 0',
    date: 'DAY 2 // 04:30 PM',
    era: 'Milestone Review 03',
    title: 'Review 3: Grand Pitch & Final Product Demo',
    location: 'Jury Chambers & Main Stage',
    vessel: 'Judges Evaluation Scoring Rubric',
    wielders: 'Executive Jury Panel',
    desc: '5-minute live demo + 3-minute Q&A before senior engineering directors. Judges upload confidential scores for Innovation, Technical Complexity, Execution, and UI/UX directly into the Judge Portal.'
  },
  {
    id: 'valedictory-awards',
    stone: 'all',
    stoneName: 'ALL 6 DOMAINS',
    stoneColor: '#00ff88',
    stoneRgb: '0, 255, 136',
    date: 'DAY 2 // 07:00 PM',
    era: 'Grand Finale',
    title: 'Valedictory, Gauntlet Trophy & Prize Distribution',
    location: 'Grand Auditorium',
    vessel: 'Infinity Gauntlet Trophy & ₹5,00,000 Pool',
    wielders: 'Victorious Squads & Dignitaries',
    desc: 'Admin console compiles final scores and reveals the Grand Champions across all 6 Infinity Domains. Trophy awards, sponsor credits, job offers, and fellowship inductions.'
  }
];
